spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/where
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true

logging.level:
  org.hibernate.SQL: debug

oauth:
  kakao:
    client-id: b6d872127f0fd101c5ea0675a4481f12
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com

jwt:
  secret-key: kimgaheezzanghahahaiwanttogohomerightnow12345